export const LOAD_ALL_PRODUCTS = "app/PRODUCT_CONTEXT/LOAD_ALL_PRODUCTS";
export const LOAD_ALL_PRODUCTS_SUCCESS =
  "app/PRODUCT_CONTEXT/LOAD_ALL_PRODUCTS_SUCCESS";
export const LOAD_ALL_PRODUCTS_FAILURE =
  "app/PRODUCT_CONTEXT/LOAD_ALL_PRODUCTS_FAILURE";
